Repository dhis2/dhis2-core, pull requests merged in 2019-09, with the labels that each got.

#3750 [2.33] DHIS2-7452: adds test for checking taskSummaries when import fails
  dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadataimport/MetadataImportTest.java
Labels: test

#3683 Adds test for metadata import when errors are expected
  dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/metadataimport/MetadataImportTest.java
Labels: test

#3754 fix: use program owner OU instead of registration ou when querying teis (master)
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceService.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
Labels: Ready for review

#3755 fix: use ownership ou when querying teis with program
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/DefaultProgramInstanceService.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
Labels: Ready for review

#3819 Remove PROGRAM_DATA_SYNC job type - not needed anymore
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
Labels: Waiting for release

#3823 fix: Remove program message items when deleting soft deleted program instances
  dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
  dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
Labels: Waiting for release
