Repository dhis2/dhis2-core, pull requests merged in 2020-12, with the labels that each got.

#6929 fix: Add unique constraint to program rule name property [DHIS2-9972]
  dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/programrule/hibernate/ProgramRule.hbm.xml
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleObjectBundleHook.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceProgramTest.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/duplicate_program_rule.json
  dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/existing_program_rule.json
  dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/metadata_with_program_and_programrules.json
  dhis-2/dhis-services/dhis-service-program-rule/src/test/java/org/hisp/dhis/programrule/ProgramRuleServiceTest.java
  dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_16__Set_unique_name_property_for_program_rules.sql
Labels: Ready for review

#6914 fix: [DHIS2-6642] delete relationships associated with soft deleted events (2.36)
  dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/RelationshipDeletionHandler.java
  dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_17__Remove_referenced_relationships_from_soft_deleted_events_and_enrollments.sql
  dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/HibernateDbmsManager.java
Labels: Ready for review

#6915 fix: [DHIS2-6642] delete relationships associated with soft deleted events (2.35)
  dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/RelationshipDeletionHandler.java
  dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.35/V2_35_27__Remove_referenced_relationships_from_soft_deleted_events_and_enrollments.sql
  dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/HibernateDbmsManager.java
Labels: Work In Progress

#6917 fix: [DHIS2-6642] delete relationships associated with soft deleted events (2.34)
  dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/RelationshipDeletionHandler.java
  dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.34/V2_34_29__Remove_referenced_relationships_from_soft_deleted_events_and_enrollments.sql
  dhis-2/dhis-support/dhis-support-hibernate/src/main/java/org/hisp/dhis/dbms/HibernateDbmsManager.java
Labels: Ready for review, Work In Progress

#6918 feat: DHIS2-10054: Adding new Axis and Legend support for Visualizations
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/AxisType.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/AxisV2.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/LegendDefinitions.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Line.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/StyledObject.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/Visualization.java
  dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/visualization/hibernate/Visualization.hbm.xml
  dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_18__Add_jsonb_columns_into_visualization_table.sql
  dhis-2/dhis-support/dhis-support-hibernate/src/main/resources/org/hisp/dhis/usertype/UserTypes.hbm.xml
Labels: Ready for review
