Repository dhis2/dhis2-core, pull requests merged in 2021-06, with the labels that each got.

#7968 chore: extracts the JSON path extractor lib to a module so it can be used in e2e tests
  dhis-2/dhis-support/dhis-support-test-json/pom.xml
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonArray.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonBoolean.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonCollection.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonDate.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonDocument.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonList.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonMap.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonMultiMap.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonNode.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonNumber.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonObject.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonPrimitive.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonResponse.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonString.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonURL.java
  dhis-2/dhis-support/dhis-support-test-json/src/main/java/org/hisp/dhis/webapi/json/JsonValue.java
  dhis-2/dhis-support/dhis-support-test-json/src/test/java/org/hisp/dhis/webapi/json/JsonDocumentTest.java
  dhis-2/dhis-support/dhis-support-test-json/src/test/java/org/hisp/dhis/webapi/json/JsonResponseTest.java
  dhis-2/dhis-support/dhis-support-test/pom.xml
  dhis-2/dhis-support/dhis-support-test/src/test/java/org/hisp/dhis/webapi/json/domain/DomainJsonResponseTest.java
  dhis-2/dhis-support/pom.xml
  dhis-2/dhis-web/dhis-web-api-test/pom.xml
  dhis-2/pom.xml
Labels: run-api-tests

#8102 fix: trackedEntities and Events in new tracker now supports ordering [DHIS2-11092]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/program/hibernate/HibernateProgramInstanceStore.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerEventCriteria.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/webrequest/tracker/TrackerTrackedEntityCriteria.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/tracker/export/TrackerEventsExportController.java
Labels: Ready for review, run-api-tests

#8022 fix: add authorities for ProgramStageSection Schema
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramStageSectionServiceTest.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentityfilter/TrackedEntityInstanceFilterServiceTest.java
  dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramStageInstanceFilterSchemaDescriptor.java
  dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/ProgramStageSectionSchemaDescriptor.java
  dhis-2/dhis-services/dhis-service-schema/src/main/java/org/hisp/dhis/schema/descriptors/TrackedEntityInstanceFilterSchemaDescriptor.java
  dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/FileResourceControllerTest.java
Labels: testing

#8088 fix: Fix coordinates and org. unit in event enrollments [DHIS2-10228]
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
Labels: run-api-tests

#8092 fix: Fix coordinates and org. unit in event enrollments [DHIS2-10228]
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
Labels: run-api-tests

#8093 fix: Fix coordinates and org. unit in event enrollments [DHIS2-10228]
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManager.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/AbstractJdbcEventAnalyticsManagerTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
Labels: run-api-tests

#7831 fix: DHIS2-10857: Avoid scientific notation for large numbers
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/JacksonRowDataSerializer.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/OutputFormatter.java
  dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/adapter/OutputFormatterTest.java
Labels: run-api-tests

#8123 fix: Avoid scientific notation for large numbers [DHIS2-10857]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/JacksonRowDataSerializer.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/OutputFormatter.java
  dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/adapter/OutputFormatterTest.java
Labels: run-api-tests

#8122 fix: Avoid scientific notation for large numbers [DHIS2-10857]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/JacksonRowDataSerializer.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/OutputFormatter.java
  dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/adapter/OutputFormatterTest.java
Labels: run-api-tests

#8121 fix: Avoid scientific notation for large numbers [DHIS2-10857]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/JacksonRowDataSerializer.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/adapter/OutputFormatter.java
  dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/adapter/OutputFormatterTest.java
Labels: run-api-tests

#8151 fix: Change relationship deletion handler to invalidate relationnships
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/relationship/RelationshipService.java
  dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/RelationshipDeletionHandler.java
Labels: run-api-tests

#8145 fix: Missed sufix in enrollments query [DHIS2-11291]
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
Labels: run-api-tests

#8142 fix: Class cast exception in Program Indicators [DHIS2-11292]
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/DataHandler.java
Labels: run-api-tests

#8143 fix: Class cast exception in Program Indicators [DHIS2-11292]
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handling/DataHandler.java
Labels: run-api-tests

#8141 fix: Missed sufix in enrollments query [DHIS2-11291]
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/JdbcEnrollmentAnalyticsManager.java
Labels: run-api-tests

#7944 feat: Configurable programs in event analytics [DHIS2-7879]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/parameters/AnalyticsJobParameters.java
  dhis-2/dhis-api/src/test/java/org/hisp/dhis/scheduling/JobConfigurationSerializationTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/AnalyticsTableUpdateParams.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManager.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/scheduling/AnalyticsTableJob.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/ResourceTableController.java
  dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/JobConfigurationControllerTest.java
Labels: Ready for review

#8120 fix: Make program mandatory for program events and program stage for tracker events [DHIS2-11225]
  dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventValidationTests.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/TrackerIdentifierCollector.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessor.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessorTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHookTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHookTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHookTest.java
Labels: run-api-tests

#8147 fix: Remove validations from objects deletion service in new tracker importer [DHIS2-10789]
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/DefaultTrackerObjectsDeletionService.java
Labels: run-api-tests

#8155 fix: added more importModes to program rule variable names validator [DHIS2-11273]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHook.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHookTest.java
Labels: Ready for review, run-api-tests

#8138 feat: [DHIS2-9674] - Create a system job to clean up used reserved values
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/reservedvalue/ReservedValueService.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/reservedvalue/ReservedValueStore.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobType.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/DefaultReservedValueService.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/RemoveUsedOrExpiredReservedValuesJob.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStore.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/startup/SchedulerStart.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceTest.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStoreTest.java
  dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_15__Delete_REMOVE_EXPIRED_RESERVED_VALUES_Job.sql
Labels: run-api-tests

#8159 fix: Add maintenance job for deleting invalid relationships
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/maintenance/MaintenanceService.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/maintenance/MaintenanceStore.java
  dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/DefaultMaintenanceService.java
  dhis-2/dhis-services/dhis-service-administration/src/main/java/org/hisp/dhis/maintenance/jdbc/JdbcMaintenanceStore.java
  dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/maintenance/MaintenanceServiceTest.java
  dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/MaintenanceController.java
Labels: run-api-tests

#8178 fix: [2.34] Program Rule variable import through Metadata endpoint [DHIS2-11273]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHook.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHookTest.java
Labels: Ready for review, run-api-tests

#8175 fix: Get correct program stage from preheated Program [DHIS2-11225]
  dhis-2/dhis-e2e-test/src/test/java/org/hisp/dhis/tracker/importer/events/EventValidationTests.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/converter/EventTrackerConverterService.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/mappers/ProgramMapper.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/programrule/DefaultTrackerProgramRuleService.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventCategoryOptValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/EventDateValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckOwnershipValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/EventTrackerConverterServiceTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventSecurityImportValidationTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventDateValidationHookTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHookTest.java
Labels: run-api-tests

#8177 fix: [2.35] Program Rule variable import through Metadata endpoint [DHIS2-11273]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHook.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHookTest.java
Labels: Ready for review, run-api-tests

#8176 fix: [2.36] Program Rule variable import through Metadata endpoint [DHIS2-11273]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHook.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHookTest.java
Labels: Ready for review, run-api-tests

#8197 fix: remove unused code in SpringDataValueSetStore
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/SpringDataValueSetStore.java
Labels: run-api-tests

#8205 fix: skip sharing validation when skipSharing=true
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/validation/SecurityCheck.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataImportServiceTest.java
Labels: run-api-tests

#8246 chore: setting content mime type via Header in spring Mvc tests
  dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebClient.java
Labels: run-api-tests

#8234 refactor: Refactor some validators and improved test coverage [TECH-589]
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/TrackerPreheat.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preheat/supplier/ProgramOrgUnitsSupplier.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/TrackerImportValidationContext.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckOwnershipValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentImportValidationTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EnrollmentSecurityImportValidationTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/EventImportValidationTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckDataRelationsValidationHookTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckSecurityValidationHookTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/RepeatedEventsValidationHookTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/enrollments_error-nonreg-program.json
  dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/enrollments_error-program-tet-mismatch-te.json
  dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/enrollments_orgunit-mismatch.json
  dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/events-with-ou-not-in-program.json
  dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/events_error-different-program-program-stage-enrollment.json
  dhis-2/dhis-services/dhis-service-tracker/src/test/resources/tracker/validations/events_tei-not-enrolled.json
Labels: run-api-tests

#8257 feat: Gist API - include fields of references without endpoint [DHIS2-11323]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/report/Report.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/gist/GistPlanner.java
  dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/GistFieldsControllerTest.java
Labels: run-api-tests

#8220 fix: program rule variable name check now also check UID to prevent duplicates [DHIS2-11330]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHook.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/ProgramRuleVariableObjectBundleHookTest.java
Labels: Ready for review, run-api-tests

#8261 fix: Add unit test for check ownership validator [TECH-589]
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckOwnershipValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreOwnershipValidationHookTest.java
Labels: run-api-tests

#8237 feat: add import conflict data to data value set import [DHIS2-4414]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/datavalue/DefaultAggregateAccessManager.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueImportConflict.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSet.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportConflict.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidator.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/DefaultDataValueSetService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/datavalueset/ImportContext.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/importsummary/ImportConflict.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/importsummary/ImportConflictDescriptor.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/importsummary/ImportConflicts.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/importsummary/ImportSummary.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/commons/jackson/serialization/ImportSummaryJacksonTest.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetImportValidatorTest.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/datavalueset/DataValueSetServiceTest.java
Labels: run-api-tests

#8265 chore: use long IDs for data approval [DHIS2-11370]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataapproval/DataApproval.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/dataapproval/DataApprovalAudit.java
  dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_19__Migrate_DataApproval_id_column_to_long.sql
Labels: run-api-tests

#8284 perf: Avoid intermediate collections in ObjectBundle [DHIS2-2162]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/DefaultMetadataImportService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/DefaultObjectBundleValidationService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundle.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/OrganisationUnitObjectBundleHook.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/UserObjectBundleHook.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/ObjectBundleServiceTest.java
Labels: run-api-tests

#8297 feat: Renaming Visualization column
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/visualization/LegendDefinitions.java
  dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/visualization/hibernate/Visualization.hbm.xml
  dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.37/V2_37_21__Rename_Column_in_Visualization.sql
Labels: run-api-tests

#8299 feat: Add IndicatorType in analystics meta-data resp [DHIS2-7420]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/IndicatorTypeSerializer.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/MetadataItem.java
Labels: run-api-tests

#8298 feat: Add outputIdScheme support for Event Analytics [DHIS2-11181]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventDataQueryRequest.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/EventsAnalyticsQueryCriteria.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/handler/SchemaIdResponseMapper.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/EventQueryParams.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsService.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/DefaultEventDataQueryService.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/DefaultEventAnalyticsServiceTest.java
Labels: run-api-tests

#8292 fix: LazyInitializationException when search for TEI [2.37]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
Labels: run-api-tests

#8290 fix: LazyInitializationException when search for TEI [2.35]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/EventService.java
Labels: run-api-tests

#8291 fix: LazyInitializationException when search for TEI [2.36]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/AbstractEventService.java
Labels: run-api-tests

#8309 fix: Do not hard delete events in importer [DHIS2-11375]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/event/JdbcEventStore.java
Labels: run-api-tests

#8310 fix: fix acl error in event import to correctly reference the event [DHIS2-11376]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/shared/validation/BaseEventAclCheck.java
Labels: run-api-tests

#8279 feat: Improve Reserved Values generation [DHIS2-11305] [2.37]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/reservedvalue/ReservedValueStore.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/DefaultReservedValueService.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/RandomGeneratorService.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/ValueGeneratorService.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStore.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/util/Constants.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/RandomGeneratorServiceTest.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceIntegrationTest.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/ReservedValueServiceTest.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/reservedvalue/hibernate/HibernateReservedValueStoreTest.java
Labels: run-api-tests

#8342 chore: addresses sonar warnings in CSV import service
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/csv/DefaultCsvImportService.java
Labels: run-api-tests
