Repository dhis2/dhis2-core, pull requests merged in 2021-12, with the labels that each got.

#9359 fix: validate program stage reference to program DHIS2-12123
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessor.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/preprocess/EventWithoutRegistrationPreProcessor.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/report/TrackerErrorCode.java
  dhis-2/dhis-services/dhis-service-tracker/src/main/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHook.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventProgramPreProcessorTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preprocess/EventWithoutRegistrationPreProcessorTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMandatoryFieldsValidationHookTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/PreCheckMetaValidationHookTest.java
Labels: run-api-tests

#9355 chore(deps): update random beans
  dhis-2/dhis-api/pom.xml
  dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/BaseDimensionalObjectTest.java
  dhis-2/dhis-services/dhis-service-administration/src/test/java/org/hisp/dhis/dataintegrity/DataIntegrityServiceTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/DataQueryServiceDimensionItemKeywordTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EnrollmentAnalyticsManagerTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/ProgramIndicatorSubqueryBuilderTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/programindicator/RelationshipTypeJoinGeneratorTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/table/JdbcEventAnalyticsTableManagerTest.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/expression/ExpressionService2Test.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/program/ProgramSqlGeneratorVariablesTest.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/relationship/JacksonRelationshipServiceTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/bundle/TrackerImporterServiceTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/converter/NotesConverterServiceTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/PeriodTypeSupplierTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/ProgramInstanceSupplierTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/UserSupplierTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/strategy/AbstractSchemaStrategyCachingTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/preheat/supplier/strategy/TrackerEntityInstanceStrategyTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/report/TrackerImportReportTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EnrollmentNoteValidationHookTest.java
  dhis-2/dhis-services/dhis-service-tracker/src/test/java/org/hisp/dhis/tracker/validation/hooks/EventNoteValidationHookTest.java
  dhis-2/dhis-support/dhis-support-test/pom.xml
  dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/random/BeanRandomizer.java
  dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/random/GeometryRandomizer.java
  dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/random/IdRandomizer.java
  dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/random/PeriodTypeRandomizer.java
  dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/random/UidRandomizer.java
  dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/dataelement/DataElementOperandControllerTest.java
  dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/mapping/GeoFeatureControllerTest.java
  dhis-2/dhis-web-api/src/test/java/org/hisp/dhis/webapi/controller/tracker/TrackerBundleParamsConverterTest.java
  dhis-2/pom.xml
Labels: run-api-tests

#9309 chore(deps): update hamcrest to 2.2
  dhis-2/dhis-api/pom.xml
  dhis-2/dhis-services/dhis-service-administration/pom.xml
  dhis-2/dhis-services/dhis-service-analytics/pom.xml
  dhis-2/dhis-services/dhis-service-core/pom.xml
  dhis-2/dhis-services/dhis-service-dxf2/pom.xml
  dhis-2/dhis-services/dhis-service-node/pom.xml
  dhis-2/dhis-services/dhis-service-reporting/pom.xml
  dhis-2/dhis-services/dhis-service-schema/pom.xml
  dhis-2/dhis-services/dhis-service-tracker/pom.xml
  dhis-2/dhis-support/dhis-support-artemis/pom.xml
  dhis-2/dhis-support/dhis-support-cache-invalidation/pom.xml
  dhis-2/dhis-support/dhis-support-hibernate/pom.xml
  dhis-2/dhis-support/dhis-support-system/pom.xml
  dhis-2/dhis-support/dhis-support-test/pom.xml
  dhis-2/dhis-web-api-test/pom.xml
  dhis-2/dhis-web-api/pom.xml
  dhis-2/pom.xml
Labels: run-api-tests

#9370 chore: clean dhis-service poms
  dhis-2/dhis-services/dhis-service-acl/pom.xml
  dhis-2/dhis-services/dhis-service-schema/pom.xml
  dhis-2/dhis-services/dhis-service-setting/pom.xml
  dhis-2/dhis-services/pom.xml
  dhis-2/pom.xml
Labels: run-api-tests

#9369 fix: dhis-services should also target JDK11
  dhis-2/dhis-services/dhis-service-core/pom.xml
Labels: run-api-tests

#9415 fix: duplicate quotes prevent ACL users sharing to work DHIS2-11557 [2.36]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStore.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStoreTest.java
Labels: run-api-tests

#9433 fix: duplicate quotes prevent users sharing to work DHIS2-11557 (#9415) [2.37]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStore.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStoreTest.java
Labels: run-api-tests

#9434 fix: duplicate quotes prevent users sharing to work DHIS2-11557 (#9415)
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStore.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/trackedentity/store/DefaultAclStoreTest.java
Labels: run-api-tests

#9402 feat: remove usage of Jackson XML message converter
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/MvcTestConfig.java
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/MaintenanceControllerTest.java
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/MetadataImportExportControllerTest.java
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/UserControllerTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/CrudControllerAdvice.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/mvc/messageconverter/XmlPathMappingJackson2XmlHttpMessageConverter.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/security/config/WebMvcConfig.java
Labels: run-api-tests

#9412 ci: adds GA job to publish docker images
  .github/workflows/run-api-tests.yml
Labels: publish-docker-image

#9460 fix: Event report download response has wrong content-disposition hea…
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/EventAnalyticsController.java
Labels: Ready for review

#9345 feat: prevent simultaneous jobs in a cluster [DHIS2-12018]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/Cache.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/LocalCache.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/cache/NoOpCache.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/scheduling/JobProgress.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/AbstractSchedulingManager.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/scheduling/DefaultSchedulingManager.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/scheduling/SchedulingManagerTest.java
  dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CacheProvider.java
  dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/CappedLocalCache.java
  dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/DefaultCacheProvider.java
  dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/cache/RedisCache.java
  dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/cache/TestCache.java
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/WebTestConfiguration.java
Labels: run-api-tests

#9471 [2.38-DHIS2-TECH842] Grid Caching is not properly used in analytics
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/MetadataItem.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/cache/AnalyticsCache.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/cache/AnalyticsCacheTest.java
Labels: Ready for review

#9506 fix: DHIS2 Can’t finish the analytic in version 2.37.1 [2.38-DHIS2-TECH899]
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/table/JdbcAnalyticsTableManager.java
Labels: Ready for review

#9515 feat: Isolated 'legacy' report/chart from event visualization [TECH-867]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventchart/EventChart.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/eventreport/EventReport.java
  dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventchart/EventChart.hbm.xml
  dhis-2/dhis-services/dhis-service-core/src/main/resources/org/hisp/dhis/eventreport/EventReport.hbm.xml
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/EventChartControllerTest.java
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/EventReportControllerTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventChartController.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventReportController.java
Labels: run-api-tests

#9325 feat: Support valueType and optionSet in /eventReports [TECH-843]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseDimensionalObject.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/DimensionalObject.java
  dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/BaseAnalyticalObjectTest.java
Labels: run-api-tests

#9520 fix: Retrieve list of teis order by created using teiId [DHIS2-12260]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
Labels: run-api-tests

#9368 chore: trim event import check logic
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/config/ServiceConfig.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventChecker.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventImporterValidationRunner.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/EventManager.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/ValidatingEventChecker.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/delete/validation/DeleteValidatingEventChecker.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/insert/validation/InsertValidatingEventChecker.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/importer/update/validation/UpdateValidatingEventChecker.java
Labels: run-api-tests

#9374 fix: breaking flyway script that blocks 2.35 to 2.36 migration (2.36)
  dhis-2/dhis-support/dhis-support-db-migration/src/main/java/org/hisp/dhis/db/migration/v36/V2_36_6__Remove_duplicate_mappings_from_programstage_to_usergroups.java
  dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_10__Rename_column_programid_in_programstageusergroupaccesses.sql
  dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_50__Script_to_rename_column_programid_in_programstageusergroupaccesses_moved_to_2_36_6_and_this_script_updates_constraint_in_programstageinstance.sql
Labels: run-api-tests

#9519 fix: Retrieve list of teis order by created using teiId [DHIS2-12260]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
Labels: run-api-tests
