Repository dhis2/dhis2-core, pull requests merged in 2022-10, with the labels that each got.

#11981 ci: use jib to build DHIS2 Docker image TECH-1433
  .github/workflows/run-api-tests.yml
  README.md
  dhis-2/build-dev.sh
  dhis-2/dhis-e2e-test/docker-compose.e2e.yml
  dhis-2/dhis-e2e-test/docker-compose.yml
  dhis-2/dhis-web/dhis-web-portal/pom.xml
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/opt/dhis2/.include
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/usr/local/tomcat/conf/Catalina/localhost/.include
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/usr/local/tomcat/conf/server.xml
  docker-compose.yml
  docker/README.md
  docker/build-containers.sh
  docker/cleanup-images.sh
  docker/dhis.conf
  docker/extract-artifacts.sh
  docker/publish-containers.sh
  docker/shared/containers-list.sh
  docker/shared/wait-for-it.sh
  docker/tomcat-debian/Dockerfile
  docker/tomcat-debian/docker-entrypoint.sh
  jenkinsfiles/canary
  jenkinsfiles/dev
  jenkinsfiles/eos
  jenkinsfiles/publish-image
  jenkinsfiles/stable
Labels: publish-docker-image

#12053 ci: use jib to build DHIS2 Docker image TECH-1433 [2.38]
  .github/workflows/run-api-tests.yml
  README.md
  dhis-2/build-dev.sh
  dhis-2/dhis-e2e-test/docker-compose.e2e.yml
  dhis-2/dhis-e2e-test/docker-compose.yml
  dhis-2/dhis-web/dhis-web-portal/pom.xml
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/opt/dhis2/.include
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/usr/local/tomcat/conf/Catalina/localhost/.include
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/usr/local/tomcat/conf/server.xml
  docker-compose.yml
  docker/README.md
  docker/build-containers.sh
  docker/cleanup-images.sh
  docker/dhis.conf
  docker/extract-artifacts.sh
  docker/publish-containers.sh
  docker/shared/containers-list.sh
  docker/shared/wait-for-it.sh
  docker/tomcat-debian/Dockerfile
  docker/tomcat-debian/docker-entrypoint.sh
  jenkinsfiles/canary
  jenkinsfiles/dev
  jenkinsfiles/eos
  jenkinsfiles/publish-image
  jenkinsfiles/stable
Labels: publish-docker-image

#12047 ci: use db healthcheck to wait for e2e DB
  dhis-2/dhis-e2e-test/docker-compose.yml
Labels: publish-docker-image

#12052 ci: use jib to build DHIS2 Docker image TECH-1433 [2.39]
  .github/workflows/run-api-tests.yml
  README.md
  dhis-2/build-dev.sh
  dhis-2/dhis-e2e-test/docker-compose.e2e.yml
  dhis-2/dhis-e2e-test/docker-compose.yml
  dhis-2/dhis-web/dhis-web-portal/pom.xml
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/opt/dhis2/.include
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/usr/local/tomcat/conf/Catalina/localhost/.include
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/usr/local/tomcat/conf/server.xml
  docker-compose.yml
  docker/README.md
  docker/build-containers.sh
  docker/cleanup-images.sh
  docker/dhis.conf
  docker/extract-artifacts.sh
  docker/publish-containers.sh
  docker/shared/containers-list.sh
  docker/shared/wait-for-it.sh
  docker/tomcat-debian/Dockerfile
  docker/tomcat-debian/docker-entrypoint.sh
  jenkinsfiles/canary
  jenkinsfiles/dev
  jenkinsfiles/eos
  jenkinsfiles/publish-image
  jenkinsfiles/stable
Labels: publish-docker-image

#12054 ci: use jib to build DHIS2 Docker image TECH-1433 [2.37]
  .github/workflows/run-api-tests.yml
  README.md
  dhis-2/build-dev.sh
  dhis-2/dhis-e2e-test/Dockerfile
  dhis-2/dhis-e2e-test/docker-compose.e2e.yml
  dhis-2/dhis-e2e-test/docker-compose.yml
  dhis-2/dhis-web/dhis-web-portal/pom.xml
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/opt/dhis2/.include
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/usr/local/tomcat/conf/Catalina/localhost/.include
  dhis-2/dhis-web/dhis-web-portal/src/main/jib/usr/local/tomcat/conf/server.xml
  docker-compose.yml
  docker/README.md
  docker/build-containers.sh
  docker/cleanup-images.sh
  docker/dhis.conf
  docker/extract-artifacts.sh
  docker/publish-containers.sh
  docker/shared/containers-list.sh
  docker/shared/wait-for-it.sh
  docker/tomcat-alpine/Dockerfile
  docker/tomcat-alpine/docker-entrypoint.sh
  docker/tomcat-debian/Dockerfile
  docker/tomcat-debian/docker-entrypoint.sh
  jenkinsfiles/canary
  jenkinsfiles/dev
  jenkinsfiles/eos
  jenkinsfiles/publish-image
  jenkinsfiles/stable
Labels: publish-docker-image

#12065 ci: use JRE base image for DHIS2 Docker image TECH-1457
  dhis-2/dhis-web/dhis-web-portal/pom.xml
  jenkinsfiles/dev
  jenkinsfiles/stable
Labels: publish-docker-image

#12083 ci: improve e2e test Docker workflow
  .github/workflows/run-api-tests.yml
  Dockerfile
  README.md
  dhis-2/dhis-e2e-test/Dockerfile
  dhis-2/dhis-e2e-test/README.md
  dhis-2/dhis-e2e-test/config/dhis2_home/dhis.conf
  dhis-2/dhis-e2e-test/docker-compose.e2e.yml
  dhis-2/dhis-e2e-test/docker-compose.yml
  docker-compose.yml
  docker/dhis.conf
  jenkinsfiles/dev
  jenkinsfiles/stable
Labels: publish-docker-image

#12129 fix: Updating relationships through /trackedentityinstances endpoint shows error 500 [ DHIS2-13919 ]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
  dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
Labels: Ready for review, run-api-tests

#12167 fix: Updating relationships through /trackedentityinstances endpoint shows error 500 [ DHIS2-13919 ] [ 2.39 ]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
  dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
Labels: run-api-tests

#12168 fix: Updating relationships through /trackedentityinstances endpoint shows error 500 [ DHIS2-13919 ] [ 2.39.0 ]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
  dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
Labels: run-api-tests

#12169 fix: Improve option codes handling in analytics events [DHIS2-13953]
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/QueryItemHelper.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/QueryItemHelperTest.java
  dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceMetadataTest.java
Labels: run-api-tests, publish-docker-image

#12180 fix: Updating relationships through /trackedentityinstances endpoint shows error 500 [ DHIS2-13919 ] [ 2.36 ]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
Labels: run-api-tests

#12179 fix: Updating relationships through /trackedentityinstances endpoint shows error 500 [ DHIS2-13919 ] [ 2.37 ]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
Labels: run-api-tests

#12178 fix: Updating relationships through /trackedentityinstances endpoint shows error 500 [ DHIS2-13919 ] [ 2.38 ]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/relationship/DefaultRelationshipService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/events/relationship/AbstractRelationshipService.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/events/RelationshipServiceTest.java
Labels: run-api-tests

#12194 fix: Improve option codes handling in analytics events [DHIS2-13953]
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/QueryItemHelper.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/QueryItemHelperTest.java
  dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceMetadataTest.java
Labels: run-api-tests

#12196 fix: Improve option codes handling in analytics events [DHIS2-13953]
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/DataQueryParams.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/AbstractAnalyticsService.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/event/data/QueryItemHelper.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/data/QueryItemHelperTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/test/java/org/hisp/dhis/analytics/event/data/EventAnalyticsServiceMetadataTest.java
Labels: run-api-tests
