Repository dhis2/dhis2-core, pull requests merged in 2022-04, with the labels that each got.

#10360 fix: Query parameter in calls to /api/trackedEntityInstances not working as expected [ DHIS2-11702 ]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
Labels: run-api-tests

#10374 fix: Query parameter in calls to /api/trackedEntityInstances not working as expected [ DHIS2-11702 ] [ 2.38 ]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
Labels: run-api-tests

#10375 fix: Query parameter in calls to /api/trackedEntityInstances not working as expected [ DHIS2-11702 ] [ 2.37 ]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/trackedentity/hibernate/HibernateTrackedEntityInstanceStore.java
  dhis-2/dhis-services/dhis-service-core/src/test/java/org/hisp/dhis/trackedentity/TrackedEntityInstanceServiceTest.java
Labels: run-api-tests

#10303 fix: (2.38) tracker data view deserialisation issues [DHIS2-12249]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/trackerdataview/TrackerDataView.java
  dhis-2/dhis-e2e-test/src/test/resources/tracker/relationshipTypes.json
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/RelationshipTypeObjectBundleHook.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/java/org/hisp/dhis/dxf2/metadata/objectbundle/hooks/RelationshipTypeObjectBundleHookTest.java
  dhis-2/dhis-support/dhis-support-test/src/main/java/org/hisp/dhis/DhisConvenienceTest.java
Labels: publish-docker-image

#10414 fix: Visualization migration issue [DHIS2-13002]
  dhis-2/dhis-support/dhis-support-db-migration/src/main/resources/org/hisp/dhis/db/migration/2.36/V2_36_55__Add_jsonb_columns_into_visualization_table_fix.sql
Labels: run-api-tests

#10451 fix: ORG_UNIT_CODE Generation fails [ DHIS2-13032 ]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/textpattern/StringMethodType.java
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/attribute/TrackedEntityAttributeControllerTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityAttributeController.java
Labels: run-api-tests

#10474 fix: ORG_UNIT_CODE Generation fails [ DHIS2-13032 ] [ 2.36 ]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/textpattern/StringMethodType.java
  dhis-2/dhis-web/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/attribute/TrackedEntityAttributeControllerTest.java
  dhis-2/dhis-web/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityAttributeController.java
Labels: run-api-tests

#10496 fix: Fix ANTLR plugin version conflict
  dhis-2/dhis-support/dhis-support-json-filtering/pom.xml
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/KeyJsonValueControllerTest.java
Labels: run-api-tests

#10476 fix: ORG_UNIT_CODE Generation fails [ DHIS2-13032 ] [ 2.37 ]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/textpattern/StringMethodType.java
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/attribute/TrackedEntityAttributeControllerTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityAttributeController.java
Labels: run-api-tests

#10470 fix: ORG_UNIT_CODE Generation fails [ DHIS2-13032 ] [ 2.38 ]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/textpattern/StringMethodType.java
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/attribute/TrackedEntityAttributeControllerTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityAttributeController.java
Labels: run-api-tests

#10456 fix: Validate rule action WARNING/ERRORONCOMPLETE without DE/TEA [DHIS2-12863]
  dhis-2/dhis-services/dhis-service-dxf2/src/main/java/org/hisp/dhis/dxf2/config/ServiceConfig.java
  dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/metadata_with_program_and_program_rules_with_invalid_ruleActions.json
  dhis-2/dhis-services/dhis-service-dxf2/src/test/resources/dxf2/metadata_with_program_and_program_rules_with_valid_ruleActions.json
Labels: run-api-tests

#10424 feat: Add parameter to fetch trigram indexable attributes [DHIS2-12048] (2.39)
  dhis-2/dhis-web-api-test/src/test/java/org/hisp/dhis/webapi/controller/TrackedEntityAttributeControllerTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AbstractFullReadOnlyController.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventChartController.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/EventReportController.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/event/TrackedEntityAttributeController.java
Labels: Ready for review
