Repository dhis2/dhis2-core, pull requests merged in 2025-07, with the labels that each got.

#21340 fix: Sort columns/rows + limit flag [DHIS2-19028]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CombinationGenerator.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
  dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/CombinationGeneratorTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
  dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
  dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
  dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/ValidationHelper.java
  dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryDv16AutoTest.java
  dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/generator/scenarios/aggregated.json
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AnalyticsController.java
Labels: run-api-analytics-tests

#21341 fix: Sort columns/rows + limit flag [DHIS2-19028]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CombinationGenerator.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SystemSettings.java
  dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/CombinationGeneratorTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
  dhis-2/dhis-services/dhis-service-setting/src/test/java/org/hisp/dhis/setting/SystemSettingsTest.java
  dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
  dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/ValidationHelper.java
  dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryDv16AutoTest.java
  dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/generator/scenarios/aggregated.json
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AnalyticsController.java
Labels: run-api-analytics-tests

#21343 fix: Sort columns/rows + limit flag [DHIS2-19028]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CombinationGenerator.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SettingKey.java
  dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/CombinationGeneratorTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
  dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
  dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/ValidationHelper.java
  dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryDv16AutoTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AnalyticsController.java
Labels: run-api-analytics-tests

#21346 fix: Sort columns/rows + limit flag [DHIS2-19028]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/CombinationGenerator.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/feedback/ErrorCode.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/setting/SettingKey.java
  dhis-2/dhis-api/src/test/java/org/hisp/dhis/common/CombinationGeneratorTest.java
  dhis-2/dhis-services/dhis-service-analytics/src/main/java/org/hisp/dhis/analytics/data/DefaultAnalyticsService.java
  dhis-2/dhis-support/dhis-support-system/src/main/java/org/hisp/dhis/system/grid/GridUtils.java
  dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/ValidationHelper.java
  dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/analytics/aggregate/AnalyticsQueryDv16AutoTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AnalyticsController.java
Labels: run-api-analytics-tests

#20981 chore: docker image with embedded tomcat
  .github/workflows/run-api-tests.yml
  dhis-2/build-dev.sh
  dhis-2/dhis-web-server/pom.xml
  docker/dhis.conf
  jenkinsfiles/dev
Labels: deploy

#21377 fix(DHIS-19708): ensure manifest activities field is always populated
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
Labels: deploy

#21423 fix(DHIS-19708): ensure manifest activities field is always populated [v41]
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/appmanager/AppManager.java
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
  dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/app/AppManagerTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/AppController.java
Labels: deploy, backport

#21426 fix(DHIS-19708): ensure manifest activities field is always populated [v39]
  dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/appmanager/DefaultAppManager.java
  dhis-2/dhis-test-e2e/src/test/java/org/hisp/dhis/scheduling/SchedulingTest.java
Labels: deploy, backport

#21463 fix(DHIS2-19863): expose code field in ApiToken
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/ApiKeyTokenGenerator.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/ApiToken.java
  dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/security/apikey/ApiTokenServiceImplTest.java
  dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MeControllerTest.java
  dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/security/ApiTokenAuthenticationTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/ApiTokenController.java
Labels: deploy, backport

#21464 fix(DHIS2-19863): expose code field in ApiToken
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/ApiKeyTokenGenerator.java
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/security/apikey/ApiToken.java
  dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/security/apikey/ApiTokenServiceImplTest.java
  dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/controller/MeControllerTest.java
  dhis-2/dhis-test-web-api/src/test/java/org/hisp/dhis/webapi/security/ApiTokenAuthenticationTest.java
  dhis-2/dhis-web-api/src/main/java/org/hisp/dhis/webapi/controller/security/ApiTokenController.java
Labels: deploy, backport

#21501 fix: metadata export of visualization relative periods
  dhis-2/dhis-api/src/main/java/org/hisp/dhis/common/BaseAnalyticalObject.java
  dhis-2/dhis-test-integration/src/test/java/org/hisp/dhis/dxf2/metadata/MetadataExportServiceTest.java
Labels: run-api-analytics-tests
